apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-shopping-cart-order
  name: ctse-shopping-cart-order
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ctse-shopping-cart-order
status:
  loadBalancer: {}